"""describe change

Revision ID: 579fbf1df0d0
Revises: a1156a626d94
Create Date: 2025-09-12 01:46:21.095833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579fbf1df0d0'
down_revision: Union[str, Sequence[str], None] = 'a1156a626d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.alter_column('user_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_logs', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_logs', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_logs', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_logs', 'load',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'created_at')
    op.add_column('workouts', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('workouts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workouts', 'default_sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'default_reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workouts', 'default_load',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'default_load',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('workouts', 'default_reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'default_sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('workouts', 'description')
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_logs', 'load',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_logs', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_logs', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_logs', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gif_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###
